/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bonsspassos.loja.edicao;

import com.bonsspassos.loja.consulta.ConsultaProduto;
import com.bonsspassos.loja.model.Produto;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author RSG
 */
public class EditaProduto extends javax.swing.JFrame {

    List<Produto> produtos = new ArrayList<>();

    public EditaProduto() {
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        departamentoProd = new javax.swing.JComboBox<>();
        qtdProduto = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tamanhoProduto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        modeloProduto = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        marcaProduto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        valorProduto = new javax.swing.JTextField();
        btnCadastroProduto = new javax.swing.JButton();

        setTitle("LOJA BONS PASSOS - EDITA PRODUTOS");
        setResizable(false);

        jLabel1.setText("Produto:");

        nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Departamento:");

        departamentoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Streetwear", "Corrida", "Academia e Treino", "Chuteiras", "Basquete", "Sandalias e Chinelos" }));
        departamentoProd.setToolTipText("");
        departamentoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoProdActionPerformed(evt);
            }
        });

        qtdProduto.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        jLabel4.setText("Tamanho:");

        tamanhoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "34", "36", "38", "40", "41", "42", "43", "44", "45", "46", "47", "48" }));
        tamanhoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanhoProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Modelo:");

        modeloProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Unissex" }));
        modeloProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca:");

        marcaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nike", "Tesla", "Adidas", "Mizuno", "DC Shoes", "QIX", "Puma", "Vans", "New Balance", "Hocks" }));
        marcaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor:");

        jLabel8.setText("CADASTRO DE PRODUTOS");

        btnCadastroProduto.setText("Salvar");
        btnCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departamentoProd, 0, 233, Short.MAX_VALUE)
                            .addComponent(modeloProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tamanhoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(valorProduto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(qtdProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                    .addComponent(btnCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(marcaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeProduto))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(marcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(departamentoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modeloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tamanhoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(qtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(valorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProdutoActionPerformed

    }//GEN-LAST:event_nomeProdutoActionPerformed

    private void departamentoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoProdActionPerformed

    }//GEN-LAST:event_departamentoProdActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed
        Produto produto = new Produto();
        List<String> result = validaCamposProduto(nomeProduto, valorProduto);
        String nome = nomeProduto.getText();
        String marca = (String) marcaProduto.getSelectedItem();
        String departamento = (String) departamentoProd.getSelectedItem();
        String modelo = (String) modeloProduto.getSelectedItem();
        int tamanho = Integer.parseInt((String) tamanhoProduto.getSelectedItem());
        int quantidade = (Integer) qtdProduto.getValue();
        String valor = valorProduto.getText();

        int op1 = JOptionPane.showConfirmDialog(rootPane,
            "Produto: " + nome
            + "\nDepartamento: " + departamento
            + "\nMarca: " + marca
            + "\nModelo: " + modelo
            + "\nTamanho: " + tamanho
            + "\nQuantidade: " + quantidade
            + "\nValor: "  + valor
            + "\nConfirmar cadastro deste produto?");

        if (result.size() == 0) {
            produto.setNomeProduto(nomeProduto.getText());
            produto.setMarcaProduto(marcaProduto.getSelectedItem().toString());
            produto.setDepartamentoProd(departamentoProd.getSelectedItem().toString());
            produto.setModeloProduto(modeloProduto.getSelectedItem().toString());
            produto.setTamanhoProduto(Integer.parseInt(tamanhoProduto.getSelectedItem().toString()));
            produto.setQtdProduto(Integer.parseInt(qtdProduto.getValue().toString()));
            produto.setValorProduto(valorProduto.getText());
            int op = JOptionPane.showConfirmDialog(rootPane,"Confirmar edição?\n\n" + produto + "\n\n","CONFIRME OS DADOS DO PRODUTO",JOptionPane.YES_NO_CANCEL_OPTION);
            switch (op) {
                case JOptionPane.YES_OPTION:
                JOptionPane.showMessageDialog(rootPane, "Edição realizada com sucesso!", "Edição concluida", JOptionPane.INFORMATION_MESSAGE);
                produtos.add(produto);
                ConsultaProduto.bufferProduto(produtos);
                break;
                case JOptionPane.NO_OPTION:
                break;
                case JOptionPane.CANCEL_OPTION:
                break;

            }
        }

    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    public void preencheCampos(List<Produto> produtos,Object valor, String atributo) {

        Map<Object, Produto> mapProduto = new HashMap<>();
        for (Produto produto : produtos) {
            switch (atributo) {
                case "ID":
                    mapProduto.put(valor, produto);
                   break;
                case "Produto":
                    mapProduto.put(valor, produto);
                    break;
                case "Marca":
                    mapProduto.put(valor, produto);
                    break;
                case "Departamento":
                    mapProduto.put(valor, produto);
                   break;
                case "Modelo":
                    mapProduto.put(valor, produto);
                   break;
                case "Tamanho":
                    mapProduto.put(valor, produto);
                   break;
                case "Quantidade":
                    mapProduto.put(valor, produto);
                   break;
                case "Valor":
                    mapProduto.put(valor, produto);
                   break;
                
            }
            Produto result = mapProduto.get(valor);
            nomeProduto.setText(result.getNomeProduto());
            marcaProduto.setSelectedItem(result.getMarcaProduto());
            departamentoProd.setSelectedItem(result.getDepartamentoProd());
            modeloProduto.setSelectedItem(result.getModeloProduto());
            tamanhoProduto.setSelectedItem(result.getTamanhoProduto());
            qtdProduto.setValue(result.getQtdProduto());
            valorProduto.setText(result.getValorProduto());
        }
        
    }
    
    public List<String> validaCamposProduto(
            JTextField nomeProduto, 
            JTextField valorProduto
    ) {
        List<String> camposNulos = new ArrayList<String>();

        if (String.valueOf(nomeProduto.getText()).isBlank() || nomeProduto.getText() == null) {
            camposNulos.add("O campo produto deve ser preenchido!");
        }
        if (valorProduto.getText() == null) {
            camposNulos.add("O campo CPF deve ser preenchido!");
        }
        return camposNulos;
    }
    
    private void tamanhoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanhoProdutoActionPerformed

    }//GEN-LAST:event_tamanhoProdutoActionPerformed

    private void modeloProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloProdutoActionPerformed

    }//GEN-LAST:event_modeloProdutoActionPerformed

    private void marcaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaProdutoActionPerformed

    }//GEN-LAST:event_marcaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JComboBox<String> departamentoProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> marcaProduto;
    private javax.swing.JComboBox<String> modeloProduto;
    private javax.swing.JTextField nomeProduto;
    private javax.swing.JSpinner qtdProduto;
    private javax.swing.JComboBox<String> tamanhoProduto;
    private javax.swing.JTextField valorProduto;
    // End of variables declaration//GEN-END:variables
}
